// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfdubvkpyniizzipszp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZmR1YnZrcHluaWl6emlwc3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTg3ODMsImV4cCI6MjA3MDE3NDc4M30.jI2plxsKm7i5AJMTzh3ArLO1BCfBJgC5TRjAbgcoRcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});